trigger:
- main

pool:
  name: 'Default'  # Explicitly specify the default agent pool
  vmImage: 'ubuntu-latest'

variables:
  TO_PHONE_NUMBER: '9619611425'

steps:
# Step 1: Clone the GitHub Repository
- script: |
    git clone https://github.com/mudassir2222/onlinebookstore.git
    echo "Repository cloned successfully."
  displayName: "Clone GitHub Repository"

# Step 2: Send SMS Notification via Twilio
- script: |
    echo "Cloning successful. Sending SMS notification..."
    curl -X POST https://api.twilio.com/2010-04-01/Accounts/$(TWILIO_ACCOUNT_SID)/Messages.json \
    --data-urlencode "Body=Clone Successful: onlinebookstore.git" \
    --data-urlencode "From=$(TWILIO_PHONE_NUMBER)" \
    --data-urlencode "To=$(TO_PHONE_NUMBER)" \
    -u $(TWILIO_ACCOUNT_SID):$(TWILIO_AUTH_TOKEN)
  displayName: "Send SMS Notification"
