trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Clone the GitHub Repository
- task: Checkout@1
  inputs:
    repository: 'https://github.com/mudassir2222/onlinebookstore.git'
    clean: true

# Step 2: Send SMS Notification
- script: |
    echo "Cloning successful. Sending SMS notification..."
    curl -X POST https://api.twilio.com/2010-04-01/Accounts/$(TWILIO_ACCOUNT_SID)/Messages.json \
    --data-urlencode "Body=Clone Successful: onlinebookstore.git" \
    --data-urlencode "From=$(TWILIO_PHONE_NUMBER)" \
    --data-urlencode "To=$(TO_PHONE_NUMBER)" \
    -u $(TWILIO_ACCOUNT_SID):$(TWILIO_AUTH_TOKEN)
  displayName: "Send SMS Notification"
